language: javascript

branches:
  only:
    - master
    - next

before_install:
  - npm install -g grunt-cli
  - npm install phantomjs-prebuilt

install:
  - npm install

before_script:
  - grunt lint

script:
  - grunt test

